import { DevLink, Category, LinkCategory } from './types';

export const CATEGORIES: Category[] = [
  { id: 'dev-tools', label: 'Dev Tools', emoji: '🛠️', color: '#4A9EFF' },
  { id: 'design', label: 'Design', emoji: '🎨', color: '#FF6B9D' },
  { id: 'packages', label: 'Packages', emoji: '📦', color: '#F59E0B' },
  { id: 'docs', label: 'Docs', emoji: '📚', color: '#10B981' },
  { id: 'ai-tools', label: 'AI Tools', emoji: '🤖', color: '#8B5CF6' },
  { id: 'deploy', label: 'Deploy', emoji: '☁️', color: '#06B6D4' },
  { id: 'databases', label: 'Databases', emoji: '🗄️', color: '#EF4444' },
  { id: 'learning', label: 'Learning', emoji: '🎓', color: '#F97316' },
  { id: 'productivity', label: 'Productivity', emoji: '⚡', color: '#A3E635' },
  { id: 'custom', label: 'Custom', emoji: '📌', color: '#E2E8F0' },
];

const now = Date.now();

export const DEFAULT_LINKS: DevLink[] = [
  // DEV TOOLS
  {
    id: 'github',
    title: 'GitHub',
    url: 'https://github.com',
    description: 'Hosting de código y colaboración',
    category: 'dev-tools',
    favicon: 'https://github.com/favicon.ico',
    tags: ['git', 'repos', 'code'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'vscode-web',
    title: 'VS Code Web',
    url: 'https://vscode.dev',
    description: 'VS Code directamente en el navegador',
    category: 'dev-tools',
    favicon: 'https://vscode.dev/favicon.ico',
    tags: ['editor', 'ide'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'stackoverflow',
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    description: 'Comunidad de preguntas y respuestas para devs',
    category: 'dev-tools',
    favicon: 'https://stackoverflow.com/favicon.ico',
    tags: ['qa', 'community', 'help'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'regex101',
    title: 'Regex101',
    url: 'https://regex101.com',
    description: 'Editor y tester de expresiones regulares',
    category: 'dev-tools',
    favicon: 'https://regex101.com/favicon.ico',
    tags: ['regex', 'testing'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'codebeautify',
    title: 'JSON Formatter',
    url: 'https://jsonformatter.curiousconcept.com',
    description: 'Formateador y validador de JSON',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=jsonformatter.curiousconcept.com&sz=32',
    tags: ['json', 'format', 'validate'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'gitignore',
    title: 'gitignore.io',
    url: 'https://www.toptal.com/developers/gitignore',
    description: 'Generador de archivos .gitignore',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=toptal.com&sz=32',
    tags: ['git', 'gitignore'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'ray-so',
    title: 'Ray.so',
    url: 'https://ray.so',
    description: 'Crea imágenes premium de código',
    category: 'dev-tools',
    favicon: 'https://ray.so/favicon.ico',
    tags: ['code', 'screenshot', 'share'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'transform-tools',
    title: 'Transform.tools',
    url: 'https://transform.tools',
    description: 'Convierte entre JSON, TypeScript, GraphQL y más',
    category: 'dev-tools',
    favicon: 'https://transform.tools/favicon.ico',
    tags: ['convert', 'json', 'ts'],
    createdAt: now,
    visitCount: 0,
  },

  // DESIGN
  {
    id: 'figma',
    title: 'Figma',
    url: 'https://figma.com',
    description: 'Diseño UI/UX colaborativo en la nube',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=figma.com&sz=32',
    tags: ['design', 'ui', 'ux'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'dribbble',
    title: 'Dribbble',
    url: 'https://dribbble.com',
    description: 'Inspiración y portafolios de diseño',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=dribbble.com&sz=32',
    tags: ['inspiration', 'design'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'uiverse',
    title: 'uiverse.io',
    url: 'https://uiverse.io',
    description: 'Elementos CSS y Tailwind listos para usar',
    category: 'design',
    favicon: 'https://uiverse.io/favicon.ico',
    tags: ['css', 'components', 'ui'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'coolors',
    title: 'Coolors',
    url: 'https://coolors.co',
    description: 'Generador de paletas de colores',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=coolors.co&sz=32',
    tags: ['colors', 'palette'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'realtime-colors',
    title: 'Realtime Colors',
    url: 'https://realtimecolors.com',
    description: 'Visualiza paletas en una UI real en tiempo real',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=realtimecolors.com&sz=32',
    tags: ['colors', 'ui', 'palette'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'google-fonts',
    title: 'Google Fonts',
    url: 'https://fonts.google.com',
    description: 'Catálogo de fuentes web gratuitas',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=fonts.google.com&sz=32',
    tags: ['fonts', 'typography'],
    createdAt: now,
    visitCount: 0,
  },

  // PACKAGES
  {
    id: 'npm',
    title: 'npm',
    url: 'https://npmjs.com',
    description: 'Registro de paquetes de Node.js',
    category: 'packages',
    favicon: 'https://www.google.com/s2/favicons?domain=npmjs.com&sz=32',
    tags: ['node', 'packages', 'js'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'bundlephobia',
    title: 'Bundlephobia',
    url: 'https://bundlephobia.com',
    description: 'Calcula el peso de paquetes npm en el bundle',
    category: 'packages',
    favicon: 'https://www.google.com/s2/favicons?domain=bundlephobia.com&sz=32',
    tags: ['npm', 'bundle', 'size'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'pkg-tools',
    title: 'pkg-size',
    url: 'https://pkg-size.dev',
    description: 'Analizador visual de paquetes npm',
    category: 'packages',
    favicon: 'https://www.google.com/s2/favicons?domain=pkg-size.dev&sz=32',
    tags: ['npm', 'analyze'],
    createdAt: now,
    visitCount: 0,
  },

  // DOCS
  {
    id: 'devdocs',
    title: 'DevDocs',
    url: 'https://devdocs.io',
    description: 'Documentación unificada de todos los lenguajes',
    category: 'docs',
    favicon: 'https://devdocs.io/favicon.ico',
    tags: ['docs', 'reference', 'all'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'mdn',
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    description: 'Referencia de HTML, CSS y JavaScript',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=developer.mozilla.org&sz=32',
    tags: ['html', 'css', 'js', 'web'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'react-docs',
    title: 'React Docs',
    url: 'https://react.dev',
    description: 'Documentación oficial de React',
    category: 'docs',
    favicon: 'https://react.dev/favicon.ico',
    tags: ['react', 'docs'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'nextjs-docs',
    title: 'Next.js Docs',
    url: 'https://nextjs.org/docs',
    description: 'Documentación oficial de Next.js',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=nextjs.org&sz=32',
    tags: ['nextjs', 'docs'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'tailwind-docs',
    title: 'Tailwind CSS',
    url: 'https://tailwindcss.com/docs',
    description: 'Documentación oficial de Tailwind CSS',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=tailwindcss.com&sz=32',
    tags: ['tailwind', 'css', 'docs'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'typescript-docs',
    title: 'TypeScript Docs',
    url: 'https://www.typescriptlang.org/docs',
    description: 'Handbook y referencia de TypeScript',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=typescriptlang.org&sz=32',
    tags: ['typescript', 'docs'],
    createdAt: now,
    visitCount: 0,
  },

  // AI TOOLS
  {
    id: 'chatgpt',
    title: 'ChatGPT',
    url: 'https://chat.openai.com',
    description: 'Asistente AI de OpenAI',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=32',
    tags: ['ai', 'chat', 'openai'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'claude',
    title: 'Claude',
    url: 'https://claude.ai',
    description: 'AI de Anthropic para programación y razonamiento',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=claude.ai&sz=32',
    tags: ['ai', 'anthropic', 'coding'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'v0',
    title: 'v0.dev',
    url: 'https://v0.dev',
    description: 'Genera UI con AI de Vercel',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=v0.dev&sz=32',
    tags: ['ai', 'ui', 'vercel'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'perplexity',
    title: 'Perplexity',
    url: 'https://perplexity.ai',
    description: 'Motor de búsqueda potenciado con AI',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=32',
    tags: ['ai', 'search', 'research'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'cursor',
    title: 'Cursor IDE',
    url: 'https://cursor.so',
    description: 'Editor de código con AI integrada',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=cursor.so&sz=32',
    tags: ['ai', 'ide', 'editor'],
    createdAt: now,
    visitCount: 0,
  },

  // DEPLOY
  {
    id: 'vercel',
    title: 'Vercel',
    url: 'https://vercel.com',
    description: 'Despliegue de apps Next.js y frontend',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=vercel.com&sz=32',
    tags: ['deploy', 'hosting', 'nextjs'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'railway',
    title: 'Railway',
    url: 'https://railway.app',
    description: 'Despliegue de apps fullstack y bases de datos',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=railway.app&sz=32',
    tags: ['deploy', 'hosting', 'db'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'supabase',
    title: 'Supabase',
    url: 'https://supabase.com',
    description: 'Backend open source: DB, Auth y Storage',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=supabase.com&sz=32',
    tags: ['backend', 'postgres', 'auth'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'netlify',
    title: 'Netlify',
    url: 'https://netlify.com',
    description: 'Hosting para sitios estáticos y serverless',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=netlify.com&sz=32',
    tags: ['deploy', 'static', 'serverless'],
    createdAt: now,
    visitCount: 0,
  },

  // DATABASES
  {
    id: 'planetscale',
    title: 'PlanetScale',
    url: 'https://planetscale.com',
    description: 'MySQL serverless escalable en la nube',
    category: 'databases',
    favicon: 'https://www.google.com/s2/favicons?domain=planetscale.com&sz=32',
    tags: ['mysql', 'serverless', 'db'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'mongodb-atlas',
    title: 'MongoDB Atlas',
    url: 'https://cloud.mongodb.com',
    description: 'Base de datos NoSQL gestionada en la nube',
    category: 'databases',
    favicon: 'https://www.google.com/s2/favicons?domain=mongodb.com&sz=32',
    tags: ['nosql', 'mongodb', 'cloud'],
    createdAt: now,
    visitCount: 0,
  },

  // LEARNING
  {
    id: 'frontendmasters',
    title: 'Frontend Masters',
    url: 'https://frontendmasters.com',
    description: 'Cursos avanzados de frontend y JavaScript',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=frontendmasters.com&sz=32',
    tags: ['courses', 'js', 'frontend'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'roadmap-sh',
    title: 'roadmap.sh',
    url: 'https://roadmap.sh',
    description: 'Roadmaps guiados para cada stack tecnológico',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=roadmap.sh&sz=32',
    tags: ['roadmap', 'career', 'guide'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'theodinproject',
    title: 'The Odin Project',
    url: 'https://www.theodinproject.com',
    description: 'Currículo gratuito de desarrollo web completo',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=theodinproject.com&sz=32',
    tags: ['fullstack', 'free', 'curriculum'],
    createdAt: now,
    visitCount: 0,
  },

  // PRODUCTIVITY
  {
    id: 'excalidraw',
    title: 'Excalidraw',
    url: 'https://excalidraw.com',
    description: 'Pizarra colaborativa con estilo dibujado a mano',
    category: 'productivity',
    favicon: 'https://excalidraw.com/favicon.ico',
    tags: ['whiteboard', 'diagrams', 'sketch'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'crontab-guru',
    title: 'Crontab Guru',
    url: 'https://crontab.guru',
    description: 'Editor visual de expresiones cron',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=crontab.guru&sz=32',
    tags: ['cron', 'schedule', 'linux'],
    createdAt: now,
    visitCount: 0,
  },
];

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find(c => c.id === id);
}
