import { DevLink, Category, LinkCategory } from './types';

export const CATEGORIES: Category[] = [
  { id: 'dev-tools', label: 'Dev Tools', color: '#ffffff' },
  { id: 'design', label: 'Design', color: '#ffffff' },
  { id: 'packages', label: 'Packages', color: '#ffffff' },
  { id: 'docs', label: 'Docs', color: '#ffffff' },
  { id: 'ai-tools', label: 'AI', color: '#ffffff' },
  { id: 'deploy', label: 'Deploy', color: '#ffffff' },
  { id: 'databases', label: 'Databases', color: '#ffffff' },
  { id: 'learning', label: 'Learning', color: '#ffffff' },
  { id: 'productivity', label: 'Productivity', color: '#ffffff' },
  { id: 'custom', label: 'Custom', color: '#ffffff' },
];

const now = Date.now();

export const DEFAULT_LINKS: DevLink[] = [
  // DEV TOOLS
  {
    id: 'github',
    title: 'GitHub',
    url: 'https://github.com',
    description: 'La plataforma líder mundial de desarrollo de software y control de versiones. Permite alojar repositorios Git, colaborar en proyectos de código abierto, gestionar incidencias, revisar código mediante Pull Requests y automatizar flujos de trabajo con GitHub Actions. Es el hogar de millones de desarrolladores y el estándar de facto para compartir código.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=github.com&sz=64',
    tags: ['git', 'repos', 'code'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'vscode-web',
    title: 'VS Code Web',
    url: 'https://vscode.dev',
    description: 'Versión ligera y nativa web del popular editor Visual Studio Code. Permite abrir y editar código directamente desde el navegador sin necesidad de instalar nada. Ofrece soporte para extensiones compatibles con la web, sincronización de configuraciones, temas y la capacidad de conectarse a repositorios remotos o editar archivos locales básicos.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=vscode.dev&sz=64',
    tags: ['editor', 'ide'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'stackoverflow',
    title: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    description: 'La mayor comunidad de preguntas y respuestas para programadores. Un recurso invaluable para encontrar soluciones a errores específicos, aprender mejores prácticas y compartir conocimientos técnicos sobre casi cualquier lenguaje, framework o herramienta de desarrollo. Basado en un sistema de reputación y validación por la comunidad.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=stackoverflow.com&sz=64',
    tags: ['qa', 'community'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'regex101',
    title: 'Regex101',
    url: 'https://regex101.com',
    description: 'Herramienta interactiva y visual para crear, probar y depurar expresiones regulares (Regex). Soporta múltiples motores como PCRE, JavaScript, Python, Go y Java. Incluye explicaciones detalladas paso a paso de qué hace cada parte de tu expresión, resaltado de sintaxis, pruebas de coincidencia y una biblioteca de patrones de la comunidad.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=regex101.com&sz=64',
    tags: ['regex', 'testing'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'ray-so',
    title: 'Ray.so',
    url: 'https://ray.so',
    description: 'Utilidad en línea para convertir fragmentos de código en imágenes estéticamente agradables y de alta resolución. Ideal para compartir código en redes sociales, presentaciones o artículos de blog. Ofrece resaltado de sintaxis, múltiples temas de color oscuros y claros, fondos con degradados, padding ajustable y controles de ventana estilo macOS.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=ray.so&sz=64',
    tags: ['code', 'screenshot'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'transform-tools',
    title: 'Transform.tools',
    url: 'https://transform.tools',
    description: 'Conjunto de herramientas multipropósito para transformar código y datos. Permite convertir entre formatos como HTML a JSX, JSON a interfaces de TypeScript, CSS a Tailwind, SVG a componentes React, y mucho más. Una navaja suiza esencial que ahorra horas de conversión manual al desarrollar interfaces y tipar respuestas de APIs.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=transform.tools&sz=64',
    tags: ['convert', 'json'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'gitignore',
    title: 'gitignore.io',
    url: 'https://www.toptal.com/developers/gitignore',
    description: 'Generador automático de archivos .gitignore. Simplemente introduce tu sistema operativo, editor de código e IDE, lenguajes de programación y frameworks (por ejemplo: Windows, VSCode, Node, React) y la herramienta compilará al instante un archivo .gitignore completo para evitar subir archivos basura, dependencias y configuraciones locales a tu repositorio.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=toptal.com&sz=64',
    tags: ['git', 'gitignore'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'codebeautify',
    title: 'JSON Formatter',
    url: 'https://jsonformatter.curiousconcept.com',
    description: 'Herramienta en línea robusta para formatear, embellecer y validar estructuras de datos JSON. Ayuda a leer respuestas minificadas de APIs, detecta errores de sintaxis como comas faltantes o comillas incorrectas, y permite explorar árboles JSON colapsables. Útil cuando se necesita inspeccionar payloads complejos rápidamente sin abrir un IDE.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=jsonformatter.curiousconcept.com&sz=64',
    tags: ['json', 'format'],
    createdAt: now,
    visitCount: 0,
  },

  // DESIGN
  {
    id: 'figma',
    title: 'Figma',
    url: 'https://figma.com',
    description: 'Herramienta líder de diseño de interfaces de usuario (UI) y experiencia de usuario (UX) basada en el navegador y colaborativa en tiempo real. Permite crear prototipos interactivos, sistemas de diseño robustos con auto layout y componentes variantes, y facilita el handoff (traspaso) entre diseñadores y desarrolladores. Es el estándar moderno de la industria creativa.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=figma.com&sz=64',
    tags: ['design', 'ui'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'dribbble',
    title: 'Dribbble',
    url: 'https://dribbble.com',
    description: 'Plataforma y comunidad global donde diseñadores, ilustradores y creativos comparten su trabajo, portafolios e ideas visuales ("shots"). Es una excelente fuente de inspiración diaria para explorar tendencias actuales en diseño web, aplicaciones móviles, branding, animaciones y paletas de colores antes de iniciar un nuevo proyecto.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=dribbble.com&sz=64',
    tags: ['inspiration', 'design'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'uiverse',
    title: 'uiverse.io',
    url: 'https://uiverse.io',
    description: 'Biblioteca open-source de componentes UI interactivos (botones, checkboxes, toggles, loaders, tarjetas) creados con CSS puro y Tailwind CSS. Los elementos son subidos por la comunidad, ofrecen un diseño moderno y atractivo, y están listos para ser copiados y pegados en tus proyectos para darles un toque premium sin necesidad de escribir el CSS desde cero.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=uiverse.io&sz=64',
    tags: ['css', 'components'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'coolors',
    title: 'Coolors',
    url: 'https://coolors.co',
    description: 'Generador súper rápido de paletas de colores. Permite pulsar la barra espaciadora para crear combinaciones armoniosas aleatorias, bloquear colores específicos, extraer colores de una imagen subida, comprobar el contraste para la accesibilidad y exportar las paletas en múltiples formatos (CSS, SCSS, SVG, PDF).',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=coolors.co&sz=64',
    tags: ['colors', 'palette'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'realtime-colors',
    title: 'Realtime Colors',
    url: 'https://realtimecolors.com',
    description: 'Herramienta de visualización de colores en contexto. En lugar de ver cuadrados de color aislados, esta web te permite simular cómo se verá una paleta de colores completa (texto principal, fondo, color primario, secundario, bordes) aplicada directamente a una landing page de ejemplo completa con tipografías, botones, gráficos y secciones reales.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=realtimecolors.com&sz=64',
    tags: ['colors', 'ui'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'google-fonts',
    title: 'Google Fonts',
    url: 'https://fonts.google.com',
    description: 'El mayor catálogo gratuito y open-source de fuentes tipográficas e íconos (Material Symbols) para la web. Permite explorar y probar diferentes tipografías, filtrando por estilo (serif, sans-serif, display, monospace), y proporciona los enlaces CSS necesarios o las instrucciones de importación para integrarlas rápida y fácilmente en cualquier sitio web o aplicación.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=fonts.google.com&sz=64',
    tags: ['fonts', 'typography'],
    createdAt: now,
    visitCount: 0,
  },

  // PACKAGES
  {
    id: 'npm',
    title: 'npm',
    url: 'https://npmjs.com',
    description: 'El registro de software y gestor de paquetes por defecto para el ecosistema Node.js y JavaScript. Contiene millones de paquetes, librerías, utilidades y frameworks públicos. Aquí puedes buscar módulos, leer sus archivos README, consultar versiones, métricas de descargas, repositorios fuente y enlaces a documentación de dependencias que usas diariamente.',
    category: 'packages',
    favicon: 'https://www.google.com/s2/favicons?domain=npmjs.com&sz=64',
    tags: ['node', 'packages'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'bundlephobia',
    title: 'Bundlephobia',
    url: 'https://bundlephobia.com',
    description: 'Herramienta vital para analizar el impacto en el rendimiento de añadir un paquete npm. Te indica cuánto peso agregará a tu bundle final (minificado y comprimido con Gzip), el tiempo estimado de descarga sobre diferentes redes (3G, 4G), si soporta tree-shaking, sus dependencias anidadas y sugiere alternativas más ligeras si existen.',
    category: 'packages',
    favicon: 'https://www.google.com/s2/favicons?domain=bundlephobia.com&sz=64',
    tags: ['npm', 'bundle', 'size'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'pkg-size',
    title: 'pkg-size',
    url: 'https://pkg-size.dev',
    description: 'Analizador visual interactivo para explorar el tamaño real y el contenido de un paquete npm instalado en el disco y una vez empaquetado. Proporciona una interfaz basada en explorador de archivos donde puedes examinar línea por línea los exports y descubrir por qué una librería específica está inflando el tamaño final del bundle de tu aplicación.',
    category: 'packages',
    favicon: 'https://www.google.com/s2/favicons?domain=pkg-size.dev&sz=64',
    tags: ['npm', 'analyze'],
    createdAt: now,
    visitCount: 0,
  },

  // DOCS
  {
    id: 'devdocs',
    title: 'DevDocs',
    url: 'https://devdocs.io',
    description: 'Unifica la documentación de múltiples lenguajes de programación, librerías, APIs web y frameworks (como JS, HTML, CSS, React, Python, Git) en una única interfaz de búsqueda limpia, rápida e intuitiva. Funciona sin conexión, no tiene publicidad y permite atajos de teclado para un acceso instantáneo a cualquier manual técnico desde un solo lugar.',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=devdocs.io&sz=64',
    tags: ['docs', 'reference'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'mdn',
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    description: 'Mantenida por Mozilla, es considerada universalmente como la referencia más completa y autorizada para tecnologías web estándar: HTML5, CSS3, JavaScript nativo y Web APIs. Incluye ejemplos de uso detallados, compatibilidad detallada con navegadores históricos y modernos, y guías conceptuales tanto para principiantes como para expertos.',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=developer.mozilla.org&sz=64',
    tags: ['html', 'css', 'js'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'react-docs',
    title: 'React',
    url: 'https://react.dev',
    description: 'La documentación oficial y actualizada para React. Escrita desde cero para enseñar React con componentes funcionales y Hooks como estándar. Contiene tutoriales detallados con código editable en línea ("sandboxes"), explicaciones visuales sobre el renderizado, el estado, efectos, y referencias profundas a cada API de la librería.',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=react.dev&sz=64',
    tags: ['react', 'docs'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'nextjs-docs',
    title: 'Next.js',
    url: 'https://nextjs.org/docs',
    description: 'La referencia oficial para construir aplicaciones web full-stack con Next.js, el framework de React mantenido por Vercel. Incluye documentación exhaustiva sobre el nuevo App Router (RSC, layouts, Server Actions), así como el antiguo Pages Router. Cubre enrutamiento, obtención de datos, renderizado estático/dinámico, optimizaciones de imágenes y despliegue.',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=nextjs.org&sz=64',
    tags: ['nextjs', 'docs'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'tailwind-docs',
    title: 'Tailwind CSS',
    url: 'https://tailwindcss.com/docs',
    description: 'Documentación del popular framework CSS utilitario ("utility-first"). Es conocida por ser excepcionalmente clara y fácil de navegar, con un motor de búsqueda instantáneo. Detalla cada clase disponible, su equivalente en CSS puro, cómo personalizar el archivo tailwind.config, diseño responsivo, estados (hover, focus) y directivas personalizadas.',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=tailwindcss.com&sz=64',
    tags: ['tailwind', 'css'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'typescript-docs',
    title: 'TypeScript',
    url: 'https://www.typescriptlang.org/docs',
    description: 'El manual y referencia oficial de TypeScript, el superconjunto tipado de JavaScript desarrollado por Microsoft. Ofrece explicaciones profundas desde conceptos básicos de tipado, interfaces y clases, hasta temas avanzados como genéricos, tipos condicionales, manipulación de AST y la configuración extensa de opciones en tsconfig.json.',
    category: 'docs',
    favicon: 'https://www.google.com/s2/favicons?domain=typescriptlang.org&sz=64',
    tags: ['typescript', 'docs'],
    createdAt: now,
    visitCount: 0,
  },

  // AI TOOLS
  {
    id: 'chatgpt',
    title: 'ChatGPT',
    url: 'https://chat.openai.com',
    description: 'El asistente conversacional pionero basado en IA desarrollado por OpenAI. Utiliza modelos avanzados (como GPT-4) para entender el lenguaje natural y generar código, responder preguntas técnicas complejas, redactar documentación, ayudar en el debugging y proporcionar tutoría en prácticamente cualquier lenguaje de programación o concepto de ciencias de la computación.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=chat.openai.com&sz=64',
    tags: ['ai', 'openai'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'claude',
    title: 'Claude',
    url: 'https://claude.ai',
    description: 'Asistente de inteligencia artificial de Anthropic (familia Claude 3). Conocido por sus grandes ventanas de contexto (ideal para analizar bases de código completas o documentos extensos), un tono de escritura natural, fuerte razonamiento deductivo y excelentes capacidades de programación para refactorizar o arquitectar sistemas de software complejos.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=claude.ai&sz=64',
    tags: ['ai', 'anthropic'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'v0',
    title: 'v0.dev',
    url: 'https://v0.dev',
    description: 'Una innovadora herramienta impulsada por IA creada por Vercel. Permite a los desarrolladores y diseñadores generar componentes de interfaz de usuario de React (utilizando Tailwind CSS y shadcn/ui) simplemente describiéndolos en lenguaje natural. Útil para prototipar rápidamente dashboards, tarjetas, menús de navegación y diseños de página completos.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=v0.dev&sz=64',
    tags: ['ai', 'ui', 'vercel'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'perplexity',
    title: 'Perplexity',
    url: 'https://perplexity.ai',
    description: 'Un motor de respuestas tipo IA conversacional diseñado para la búsqueda en la web. En lugar de ofrecer listas de enlaces, Perplexity investiga en tiempo real y redacta respuestas concisas y bien formateadas citando explícitamente sus fuentes y enlaces. Ideal para buscar documentación reciente, novedades de APIs y resolución rápida de problemas técnicos actuales.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64',
    tags: ['ai', 'search'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'cursor',
    title: 'Cursor',
    url: 'https://cursor.so',
    description: 'Un editor de código (bifurcado de VS Code) que integra inteligencia artificial profundamente en la experiencia de desarrollo. Permite hablar con tu código, generar implementaciones enteras a partir de comentarios (Cmd+K), entender bases de código complejas y predecir la próxima edición en múltiples líneas o archivos sin esfuerzo.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=cursor.so&sz=64',
    tags: ['ai', 'ide'],
    createdAt: now,
    visitCount: 0,
  },

  // DEPLOY
  {
    id: 'vercel',
    title: 'Vercel',
    url: 'https://vercel.com',
    description: 'La plataforma líder en el ecosistema de frontend y alojamiento serverless. Desarrollada por los creadores de Next.js, Vercel ofrece flujos de trabajo de despliegue optimizados desde repositorios Git, vistas previas de despliegue automáticas por cada Pull Request (Deploy Previews), analíticas web integradas en tiempo real y una CDN global ultrarrápida.',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=vercel.com&sz=64',
    tags: ['deploy', 'hosting'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'railway',
    title: 'Railway',
    url: 'https://railway.app',
    description: 'Una infraestructura en la nube moderna y accesible (similar al clásico Heroku). Permite aprovisionar instantáneamente bases de datos (PostgreSQL, Redis, MySQL), colas, y desplegar aplicaciones fullstack (Node, Python, Go, Docker) simplemente conectando tu repositorio de GitHub, sin tener que configurar archivos DevOps complejos.',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=railway.app&sz=64',
    tags: ['deploy', 'hosting'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'supabase',
    title: 'Supabase',
    url: 'https://supabase.com',
    description: 'Alternativa open source a Firebase. Te provee una base de datos PostgreSQL real y gestionada, APIs autogeneradas (REST y GraphQL), autenticación de usuarios integrada, almacenamiento de archivos, funciones serverless (Edge Functions) y suscripciones a datos en tiempo real mediante WebSockets. Todo gestionado desde un panel de control excelente.',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=supabase.com&sz=64',
    tags: ['backend', 'postgres'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'netlify',
    title: 'Netlify',
    url: 'https://netlify.com',
    description: 'Plataforma pionera del movimiento Jamstack. Facilita la construcción, despliegue y gestión de sitios web estáticos, aplicaciones de una sola página (SPAs) y funciones serverless sin backend tradicional. Ofrece CI/CD integrado, Netlify Forms para recolectar envíos de formularios HTML simples y Edge Handlers.',
    category: 'deploy',
    favicon: 'https://www.google.com/s2/favicons?domain=netlify.com&sz=64',
    tags: ['deploy', 'static'],
    createdAt: now,
    visitCount: 0,
  },

  // DATABASES
  {
    id: 'planetscale',
    title: 'PlanetScale',
    url: 'https://planetscale.com',
    description: 'Base de datos MySQL serverless y globalmente distribuida diseñada para la escalabilidad. Inspirada en Vitess, trae la experiencia de flujo de trabajo de Git a las bases de datos: permite crear ramas (branches) de tu esquema, probar migraciones de forma segura (non-blocking schema changes) y hacer merge de cambios en producción sin tiempos de inactividad.',
    category: 'databases',
    favicon: 'https://www.google.com/s2/favicons?domain=planetscale.com&sz=64',
    tags: ['mysql', 'serverless'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'mongodb-atlas',
    title: 'MongoDB Atlas',
    url: 'https://cloud.mongodb.com',
    description: 'El servicio de base de datos en la nube multicloud totalmente gestionado para MongoDB, la popular base de datos NoSQL basada en documentos. Despliega clústeres altamente disponibles, seguros y elásticos. Incluye herramientas como Atlas Search, Realm para backend móvil, gráficos y exploradores visuales de colecciones para facilitar el manejo de grandes volúmenes de datos.',
    category: 'databases',
    favicon: 'https://www.google.com/s2/favicons?domain=mongodb.com&sz=64',
    tags: ['nosql', 'mongodb'],
    createdAt: now,
    visitCount: 0,
  },

  // LEARNING
  {
    id: 'frontendmasters',
    title: 'Frontend Masters',
    url: 'https://frontendmasters.com',
    description: 'Plataforma de educación en línea especializada, que ofrece cursos de desarrollo web profundo y avanzado impartidos por ingenieros de las principales empresas tecnológicas del mundo (Netflix, Microsoft, Vercel, etc.). Ideal para dominar conceptos complejos de JavaScript moderno, arquitecturas de software, rendimiento web y algoritmos, más allá de los tutoriales básicos.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=frontendmasters.com&sz=64',
    tags: ['courses', 'frontend'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'roadmap-sh',
    title: 'roadmap.sh',
    url: 'https://roadmap.sh',
    description: 'El recurso definitivo impulsado por la comunidad que proporciona mapas de ruta educativos visuales, detallados y estructurados para guiar a los desarrolladores (Frontend, Backend, DevOps, React, Node, etc.). Enumera los lenguajes, frameworks, herramientas y conceptos teóricos ordenados paso a paso que uno debe aprender para progresar y destacar en roles de ingeniería de software.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=roadmap.sh&sz=64',
    tags: ['roadmap', 'career'],
    createdAt: now,
    visitCount: 0,
  },

  // PRODUCTIVITY
  {
    id: 'excalidraw',
    title: 'Excalidraw',
    url: 'https://excalidraw.com',
    description: 'Herramienta de pizarra virtual (whiteboard) centrada en la simplicidad y la velocidad para realizar dibujos informales y diagramas de arquitectura de sistemas. Utiliza un estilo visual distintivo dibujado a mano. Es altamente colaborativo, local-first (cifrado de extremo a extremo) y perfecto para sesiones de brainstorming técnico y planificación de arquitecturas antes de codificar.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=excalidraw.com&sz=64',
    tags: ['whiteboard', 'diagrams'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'crontab-guru',
    title: 'Crontab Guru',
    url: 'https://crontab.guru',
    description: 'Un editor de expresiones cron simple, rápido e interactivo en línea. Traduce inmediatamente la compleja sintaxis cron (ej. "0 22 * * 1-5") a texto legible por humanos para que los desarrolladores y sysadmins puedan programar, validar y depurar de forma segura la ejecución de scripts en segundo plano o tareas programadas en servidores, evitando errores en producción.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=crontab.guru&sz=64',
    tags: ['cron', 'schedule'],
    createdAt: now,
    visitCount: 0,
  },
  
  // MANUAL CUSTOM LINKS FROM USER
  {
    id: 'musicgpt',
    title: 'MusicGPT – Generador de Música y Sonido con IA',
    url: 'https://musicgpt.com',
    description: 'MusicGPT es un estudio de creación musical impulsado por IA que convierte texto, letras o voz en canciones completas con voces realistas y producción profesional en segundos.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=musicgpt.com&sz=64',
    tags: ['ai', 'music', 'audio'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'lovart',
    title: 'Lovart',
    url: 'https://lovart.ai',
    description: 'Lovart es un agente de diseño con IA que unifica color, maquetación y voz en un mundo de marca coherente.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=lovart.ai&sz=64',
    tags: ['ai', 'design', 'branding'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'pollo-ai',
    title: 'Pollo AI Creativa Definitiva con IA para Marketing',
    url: 'https://pollo.ai',
    description: 'Pollo AI es una suite creativa todo-en-uno que genera videos, imágenes, voces y personajes con calidad profesional (hasta 4K) para campañas de marketing, redes sociales y comercio electrónico. Su Pollo Agent convierte ideas, briefs o URLs en contenido listo para publicar (anuncios, historias, diseños) de principio a fin, manteniendo coherencia de marca con el Brand Kit (logotipos, colores, fuentes). Ofrece estilos que van del realismo al anime, movimiento cinemático, diálogos, música y efectos de sonido. Es ideal para creadores, equipos de marketing, e-commerce y agencias. Tiene un plan gratuito y los contenidos generados en planes de pago son de uso comercial.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=pollo.ai&sz=64',
    tags: ['ai', 'marketing', 'video'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'ifixit',
    title: 'iFixit – El Manual de Reparación Gratuito',
    url: 'https://es.ifixit.com',
    description: 'iFixit es una plataforma global y comunitaria que ofrece guías de reparación paso a paso gratuitas para miles de dispositivos electrónicos, electrodomésticos, vehículos y más. Cuenta con un asistente de IA (FixBot) para ayudar en las reparaciones, foros de respuestas y una tienda de piezas y herramientas de calidad (con garantía de por vida). También es un actor clave en el movimiento "Derecho a Reparar" (Right to Repair), publicando desmontajes y puntuaciones de reparabilidad para presionar por productos más duraderos y sostenibles. Su lema es: "Nadie sabe reparar todas las cosas, pero todos sabemos reparar algo".',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=es.ifixit.com&sz=64',
    tags: ['hardware', 'repair', 'community'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'tvgarden',
    title: 'TV Garden – Mira TV en vivo global y local gratis online',
    url: 'https://tvgarden.world',
    description: 'TV Garden es una plataforma gratuita que permite ver canales de televisión en vivo de todo el mundo sin necesidad de registro ni suscripción. Su característica principal es un globo terráqueo 3D interactivo que permite explorar canales por país o categoría (noticias, deportes, música, películas, etc.). También incluye un botón de "canal aleatorio" para descubrir contenido inesperado. La plataforma no aloja los streams, solo enlaza a fuentes públicas y de libre acceso (como canales gratuitos en YouTube o sitios web oficiales), recopiladas de repositorios colaborativos como IPTV-org. Es una herramienta ideal para explorar contenido cultural internacional, practicar idiomas o simplemente entretenerse viendo programación de otros países.',
    category: 'custom',
    favicon: 'https://www.google.com/s2/favicons?domain=tvgarden.world&sz=64',
    tags: ['entertainment', 'tv', 'global'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'autodraw',
    title: 'Autodraw',
    url: 'https://autodraw.com',
    description: 'AutoDraw es una herramienta experimental de dibujo con IA creada por Google.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=autodraw.com&sz=64',
    tags: ['ai', 'drawing', 'google'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'tripo-studio',
    title: 'Tripo Studio – Generador de modelos 3D con IA',
    url: 'https://studio.tripo3d.ai',
    description: 'Tripo Studio es una plataforma de creación 3D impulsada por IA desarrollada por VAST. Permite generar modelos 3D de alta calidad listos para producción en segundos a partir de texto, imágenes o incluso bocetos. Soporta modelos de hasta 2 millones de polígonos, ideales para impresión 3D, arte visual y assets para videojuegos. Ofrece funciones avanzadas como generación de mallas con topología limpia en 2 segundos, y se integra directamente con motores como Godot y Cocos. Además, cuenta con herramientas de posprocesamiento como pintura de texturas, reducción inteligente de polígonos y auto-rigging para animación.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=studio.tripo3d.ai&sz=64',
    tags: ['ai', '3d', 'modeling'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'hix-ai',
    title: 'HIX AI – Tu Espacio de Trabajo con Agentes de IA Definitivo',
    url: 'https://hix.ai',
    description: 'HIX AI es una plataforma integral de agentes de IA que combina en un solo espacio la investigación profunda, la creación de contenido (texto, imagen y vídeo), la generación de presentaciones y la asistencia en código. Su ecosistema multi-modal orquesta agentes especializados que planifican y ejecutan tareas complejas de forma autónoma, desde el análisis de mercado hasta la producción de activos de marketing completos. Integra los modelos de lenguaje más avanzados como GPT, Claude y Gemini, y es utilizado por más de 10 millones de usuarios para acelerar su flujo de trabajo.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=hix.ai&sz=64',
    tags: ['ai', 'agents', 'workspace'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'napkin-ai',
    title: 'Napkin AI – Convierte texto en diagramas y visuales con IA',
    url: 'https://napkin.ai',
    description: 'Napkin AI es una plataforma de comunicación visual que transforma tu texto en diagramas, mapas mentales, infografías y gráficos de datos. Solo pega o importa tu contenido y la IA genera los visuales más relevantes para que elijas. Luego puedes personalizar colores, fuentes y diseños, y exportar el resultado como PPT, PDF, PNG o SVG. Es ideal para presentaciones, blogs, documentos y redes sociales. Ofrece un plan gratuito con créditos semanales y soporta más de 60 idiomas, con interfaz disponible en español.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=napkin.ai&sz=64',
    tags: ['ai', 'diagrams', 'visuals'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'gemini-notebook',
    title: 'Gemini Notebook – Asistente de investigación con IA',
    url: 'https://notebook.google',
    description: 'Gemini Notebook es un asistente de investigación impulsado por el modelo Gemini que convierte tus fuentes (PDFs, sitios web, videos de YouTube, audios, Google Docs y Slides) en un experto personalizado. Resume, conecta ideas y genera respuestas con citas exactas de tus documentos, reduciendo alucinaciones. Incluye la función "Audio Overview" que crea debates tipo pódcast a partir de tu contenido. Es ideal para estudiantes, investigadores y profesionales que quieren analizar documentación, preparar presentaciones o explorar nuevas ideas. Ofrece control total sobre los datos y no usa tu contenido para entrenar modelos (a menos que compartas feedback).',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=notebook.google&sz=64',
    tags: ['ai', 'research', 'google'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'recraft-ai',
    title: 'Recraft – IA para diseñadores, creativos y equipos',
    url: 'https://recraft.ai',
    description: 'Recraft es una plataforma de generación y edición de imágenes, vectores y maquetas con IA, diseñada específicamente para profesionales del diseño. Ofrece modelos de IA con dirección de arte integrada para crear imágenes con calidad estética y atmósfera cuidada. Sus puntos fuertes son la generación de vectores complejos editables (formato SVG), la creación de estilos consistentes sin necesidad de entrenar modelos (solo subiendo imágenes de referencia) y la producción de gráficos listos para usar, incluyendo tipografía, ilustraciones y gráficos 3D. Es usado por diseñadores de empresas innovadoras y se diferencia de otros generadores por su alto nivel de control y personalización.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=recraft.ai&sz=64',
    tags: ['ai', 'design', 'vector'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'wallhaven',
    title: 'Wallhaven – Fondo de pantalla asombrosos',
    url: 'https://wallhaven.cc',
    description: 'Wallhaven es uno de los mayores repositorios de fondos de pantalla en alta calidad, con más de 1.3 millones de wallpapers disponibles. Es una comunidad activa donde los usuarios suben, etiquetan y descubren imágenes en resoluciones que van hasta 4K y superiores. Ofrece potentes filtros de búsqueda por resolución, color, relación de aspecto, y más de 113,000 etiquetas creadas por usuarios para encontrar exactamente lo que buscas. Es una excelente fuente de inspiración visual y recursos gráficos para diseñadores, desarrolladores o cualquier persona que quiera personalizar sus dispositivos.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=wallhaven.cc&sz=64',
    tags: ['design', 'wallpapers', 'assets'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'toffeeshare',
    title: 'ToffeeShare – Comparte archivos en privado.',
    url: 'https://toffeeshare.com',
    description: 'ToffeeShare es un servicio gratuito de intercambio de archivos Peer-to-Peer (P2P) que prioriza la privacidad y la velocidad. No almacena nada en la nube: los archivos se transfieren directamente entre dispositivos y desaparecen al cerrar el navegador. Ofrece sin límite de tamaño (depende solo de tu navegador y dispositivo), cifrado de extremo a extremo con DTLS 1.3, y es respetuoso con el medio ambiente (sus servidores usan energía eólica). Con más de 750,000 archivos compartidos al mes, es una alternativa ideal para enviar archivos grandes de forma segura y sin registro, perfecto para desarrolladores, diseñadores o cualquier persona que necesite compartir datos sensibles o pesados rápidamente.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=toffeeshare.com&sz=64',
    tags: ['files', 'sharing', 'p2p'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'theodinproject',
    title: 'The Odin Project',
    url: 'https://theodinproject.com',
    description: 'Currículo gratuito de desarrollo web completo.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=theodinproject.com&sz=64',
    tags: ['learning', 'course', 'webdev'],
    createdAt: now,
    visitCount: 0,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // DEV TOOLS — nuevos
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'codepen',
    title: 'CodePen',
    url: 'https://codepen.io',
    description: 'El playground online más popular para HTML, CSS y JavaScript. Permite crear, editar y compartir fragmentos de código ("pens") en vivo directamente en el navegador sin configuración. Es ideal para experimentar con ideas rápidas, ver el resultado en tiempo real, descubrir demos interesantes de la comunidad y compartir ejemplos de código con otros desarrolladores.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=codepen.io&sz=64',
    tags: ['playground', 'html', 'css', 'js'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'jsoncrack',
    title: 'JSON Crack',
    url: 'https://jsoncrack.com',
    description: 'Visualizador interactivo y gratuito que convierte datos JSON, YAML, TOML o CSV en grafos de nodos navegables y editables. En lugar de leer JSON anidado en texto plano, JSON Crack lo transforma en un diagrama visual que facilita entender estructuras complejas de APIs, respuestas de bases de datos o archivos de configuración de gran tamaño.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=jsoncrack.com&sz=64',
    tags: ['json', 'visualizer', 'tool'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'jwtio',
    title: 'JWT.io',
    url: 'https://jwt.io',
    description: 'Herramienta oficial para decodificar, verificar y generar JSON Web Tokens (JWT). Pega cualquier token y al instante decodifica su header y payload para inspeccionar los datos que contiene. Imprescindible cuando se desarrollan sistemas de autenticación, se depuran errores de autorización o se verifica que la firma y la fecha de expiración de un token son correctas.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=jwt.io&sz=64',
    tags: ['jwt', 'auth', 'token'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'caniuse',
    title: 'Can I Use',
    url: 'https://caniuse.com',
    description: 'La referencia definitiva para verificar la compatibilidad de características de HTML5, CSS3 y Web APIs en los distintos navegadores (Chrome, Firefox, Safari, Edge). Muestra tablas de soporte detalladas por versión de navegador, con notas de comportamiento, polyfills disponibles y estadísticas de cobertura global para tomar decisiones informadas sobre qué usar en producción.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=caniuse.com&sz=64',
    tags: ['css', 'html', 'browser', 'compatibility'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'webhooksite',
    title: 'Webhook.site',
    url: 'https://webhook.site',
    description: 'Genera al instante una URL única y temporal para capturar, inspeccionar y depurar solicitudes HTTP entrantes, webhooks, correos electrónicos y más. Extremadamente útil para hacer pruebas de integraciones con servicios de terceros (Stripe, GitHub, Twilio) sin necesidad de exponer tu servidor local a internet ni usar herramientas como ngrok.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=webhook.site&sz=64',
    tags: ['webhook', 'testing', 'http'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: '10015tools',
    title: '10015.io',
    url: 'https://10015.io',
    description: 'Caja de herramientas todo-en-uno con más de 120 utilidades gratuitas para desarrolladores: convertidores de código, formatters, generadores de textos Lorem Ipsum, codificadores/decodificadores Base64 y URL, generadores de UUID, compresores CSS/JS, minificadores HTML, utilidades de color, y mucho más. Todo en un solo lugar sin anuncios molestos.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=10015.io&sz=64',
    tags: ['tools', 'utilities', 'converter'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'explainshell',
    title: 'explainshell.com',
    url: 'https://explainshell.com',
    description: 'Herramienta educativa que analiza y explica visualmente cada parte de un comando de shell o terminal. Pega cualquier comando complejo (como "tar -xzvf archivo.tar.gz") y la herramienta lo desglosa palabra por palabra, señalando cada flag, opción y argumento con su descripción extraída directamente de las páginas del manual (man pages) de Linux.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=explainshell.com&sz=64',
    tags: ['linux', 'terminal', 'shell', 'reference'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'devhints',
    title: 'DevHints',
    url: 'https://devhints.io',
    description: 'Colección de hojas de referencia rápida (cheatsheets) de alta calidad para lenguajes, frameworks, herramientas y comandos: React, Vue, Bash, Vim, Markdown, Git, ES6, CSS Flexbox, y muchos más. Diseñadas para ser compactas, visuales y fáciles de escanear cuando necesitas recordar rápidamente la sintaxis exacta sin tener que buscar en la documentación completa.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=devhints.io&sz=64',
    tags: ['cheatsheet', 'reference', 'quick'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'epochconverter',
    title: 'Epoch Converter',
    url: 'https://epochconverter.com',
    description: 'Conversor de timestamps Unix (epoch time) a fechas legibles y viceversa. Esencial cuando se trabaja con APIs, bases de datos o logs que devuelven tiempos en formato epoch. También muestra la hora actual en varios formatos, convierte entre zonas horarias y proporciona ejemplos de código para múltiples lenguajes para trabajar con timestamps.',
    category: 'dev-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=epochconverter.com&sz=64',
    tags: ['timestamp', 'date', 'unix'],
    createdAt: now,
    visitCount: 0,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // DESIGN — nuevos
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'removebg',
    title: 'Remove.bg',
    url: 'https://remove.bg',
    description: 'Herramienta gratuita impulsada por IA que elimina el fondo de cualquier imagen en segundos. Funciona excepcionalmente bien con fotos de personas, animales y objetos. Ideal para crear fotos de perfil profesionales, imágenes de productos para e-commerce, stickers y composiciones sin fondo. Ofrece un plan gratuito para imágenes de resolución estándar.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=remove.bg&sz=64',
    tags: ['image', 'background', 'ai'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'squoosh',
    title: 'Squoosh',
    url: 'https://squoosh.app',
    description: 'Compresor de imágenes en el navegador creado por Google. Permite comparar en tiempo real la imagen original vs. la comprimida, ajustando la calidad para encontrar el balance perfecto entre tamaño y nitidez. Soporta múltiples formatos de salida modernos como WebP, AVIF y JXL. Es completamente gratuito, funciona sin conexión y no sube tus imágenes a ningún servidor.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=squoosh.app&sz=64',
    tags: ['image', 'compress', 'optimize'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'undraw',
    title: 'unDraw',
    url: 'https://undraw.co',
    description: 'Biblioteca abierta y gratuita de ilustraciones SVG planas y minimalistas de alta calidad, con miles de escenas para cualquier tipo de proyecto. Una característica única es que puedes cambiar el color de acento de todas las ilustraciones en tiempo real para que coincidan con la paleta de tu marca antes de descargarlas. No requiere atribución para uso.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=undraw.co&sz=64',
    tags: ['illustrations', 'svg', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'svgrepo',
    title: 'SVG Repo',
    url: 'https://svgrepo.com',
    description: 'El mayor repositorio gratuito de iconos y vectores SVG con más de 500,000 archivos SVG listos para usar. Ofrece iconos en múltiples estilos (lineal, sólido, duotono, coloreado) de paquetes populares como Material, Tabler, Fluent y muchos más. Permite buscar, personalizar colores y descargar directamente sin registro en la mayoría de los casos.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=svgrepo.com&sz=64',
    tags: ['icons', 'svg', 'vector'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'lottiefiles',
    title: 'LottieFiles',
    url: 'https://lottiefiles.com',
    description: 'Plataforma para descubrir, editar y compartir animaciones Lottie (formato JSON ligero basado en After Effects). Las animaciones Lottie son vectoriales, escalan perfectamente a cualquier resolución y son increíblemente pequeñas comparadas con GIFs o videos. Perfectas para añadir micro-interacciones y animaciones de carga premium a webs y apps sin sacrificar rendimiento.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=lottiefiles.com&sz=64',
    tags: ['animation', 'lottie', 'motion'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'haikei',
    title: 'Haikei',
    url: 'https://haikei.app',
    description: 'Generador gratuito de fondos SVG únicos y personalizables: blobs orgánicos, ondas, gradientes, polígonos, patrones de burbujas y muchos más estilos. Todos completamente editables (colores, complejidad, escala) y exportables como SVG o PNG. Ideal para crear secciones de hero, separadores y fondos modernos para webs sin necesidad de usar Figma o Illustrator.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=haikei.app&sz=64',
    tags: ['svg', 'background', 'generator'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'photopea',
    title: 'Photopea',
    url: 'https://photopea.com',
    description: 'Editor de imágenes avanzado y gratuito que funciona directamente en el navegador, compatible con los formatos de Photoshop (PSD), GIMP (XCF), Illustrator (AI), Sketch y muchos más. Ofrece una interfaz y conjunto de herramientas casi idénticos a Photoshop: capas, máscaras, ajustes, filtros, texto, formas y exportación a múltiples formatos. Sin instalación, sin suscripción.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=photopea.com&sz=64',
    tags: ['photo', 'editor', 'photoshop', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'css-gradient',
    title: 'CSS Gradient',
    url: 'https://cssgradient.io',
    description: 'Generador visual e interactivo de gradientes CSS. Permite crear gradientes lineales, radiales y cónicos con múltiples puntos de color, ajustar ángulos y posiciones, y obtener al instante el código CSS listo para copiar. También incluye una galería de gradientes predefinidos hermosos para servir de inspiración y una herramienta de gradiente de malla (mesh gradient).',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=cssgradient.io&sz=64',
    tags: ['css', 'gradient', 'generator'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'unsplash',
    title: 'Unsplash',
    url: 'https://unsplash.com',
    description: 'La biblioteca más grande y respetada de fotografías de alta resolución, completamente gratuitas y libres de derechos de autor. Más de 3 millones de fotos aportadas por fotógrafos profesionales de todo el mundo. Las imágenes son libres para uso comercial y personal sin necesidad de atribución, ideales para webs, presentaciones, portadas y materiales de marketing.',
    category: 'design',
    favicon: 'https://www.google.com/s2/favicons?domain=unsplash.com&sz=64',
    tags: ['photos', 'stock', 'free'],
    createdAt: now,
    visitCount: 0,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // PRODUCTIVITY — nuevos (conversores, utilidades personales)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'ilovepdf',
    title: 'iLovePDF',
    url: 'https://ilovepdf.com',
    description: 'Suite online completa y gratuita de herramientas para trabajar con PDFs: combinar, dividir, comprimir, convertir (PDF a Word, Excel, JPG y viceversa), rotar páginas, añadir marca de agua, organizar, proteger con contraseña y editar. Incluye 24 herramientas en un solo lugar. Soporta carga desde Google Drive y Dropbox. El plan gratuito es muy generoso para uso personal.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=ilovepdf.com&sz=64',
    tags: ['pdf', 'converter', 'tools'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'convertio',
    title: 'Convertio',
    url: 'https://convertio.co',
    description: 'Conversor de archivos online que soporta más de 300 formatos distintos: documentos (DOCX, ODS, EPUB), imágenes (JPG, PNG, WebP, HEIC), audio (MP3, WAV, FLAC), video (MP4, MKV, AVI), vectores (SVG, AI, EPS) y muchos más. Convierte hasta 100 MB gratis sin necesidad de instalar ningún software. También acepta archivos desde Google Drive y Dropbox.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=convertio.co&sz=64',
    tags: ['convert', 'files', 'format'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'deepl',
    title: 'DeepL Translator',
    url: 'https://deepl.com/translator',
    description: 'Considerado universalmente como el traductor automático de mayor calidad disponible, superando consistentemente a Google Translate en naturalidad y precisión. Utiliza redes neuronales avanzadas para capturar los matices del lenguaje. Soporta 33 idiomas y destaca especialmente en traducciones de textos técnicos, legales y formales. El plan gratuito permite hasta 500,000 caracteres al mes.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=deepl.com&sz=64',
    tags: ['translation', 'language', 'ai'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'tempmail',
    title: 'Temp Mail',
    url: 'https://temp-mail.org',
    description: 'Servicio gratuito de correo electrónico temporal y desechable. Genera al instante una dirección de email aleatoria que puede recibir mensajes durante un tiempo limitado, sin necesidad de registro. Ideal para registrarse en sitios web que requieren email pero en los que no quieres recibir spam, para verificaciones únicas o para probar flujos de email en el desarrollo.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=temp-mail.org&sz=64',
    tags: ['email', 'privacy', 'temporary'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'wetransfer',
    title: 'WeTransfer',
    url: 'https://wetransfer.com',
    description: 'Servicio gratuito para compartir archivos grandes (hasta 2 GB en el plan free) de forma sencilla y elegante. No requiere registro: sube tus archivos, introduce el email del destinatario y se envía un enlace de descarga válido por 7 días. Ideal para compartir archivos de diseño, videos, carpetas de proyectos o cualquier cosa demasiado grande para el email.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=wetransfer.com&sz=64',
    tags: ['files', 'sharing', 'transfer'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'bitwarden',
    title: 'Bitwarden',
    url: 'https://bitwarden.com',
    description: 'El gestor de contraseñas open-source más respetado y seguro disponible gratuitamente. Almacena contraseñas, notas seguras y datos de tarjetas con cifrado de extremo a extremo (AES-256). Sincroniza entre todos tus dispositivos (Windows, Mac, Linux, iOS, Android) y navegadores. El plan gratuito es ilimitado en contraseñas y dispositivos. Código fuente auditado públicamente.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=bitwarden.com&sz=64',
    tags: ['passwords', 'security', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'waybackmachine',
    title: 'Wayback Machine',
    url: 'https://web.archive.org',
    description: 'El archivo más grande de internet: más de 800,000 millones de páginas web guardadas desde 1996. Permite ver cómo lucía cualquier sitio web en una fecha específica del pasado. Útil para recuperar contenido de páginas eliminadas, investigar el historial de un sitio, leer versiones antiguas de documentación y acceder a recursos que ya no están disponibles online.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=archive.org&sz=64',
    tags: ['archive', 'internet', 'history'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'wolframalpha',
    title: 'Wolfram Alpha',
    url: 'https://wolframalpha.com',
    description: 'Motor de conocimiento computacional único: no busca páginas web, sino que calcula respuestas directas a preguntas complejas. Resuelve matemáticas (álgebra, cálculo, estadística, geometría), responde preguntas científicas, convierte unidades, analiza datos nutricionales, muestra información astronómica, geográfica y mucho más. Una calculadora superinteligente de uso gratuito.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=wolframalpha.com&sz=64',
    tags: ['math', 'science', 'calculator'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'pomofocus',
    title: 'Pomofocus',
    url: 'https://pomofocus.io',
    description: 'Temporizador Pomodoro elegante y gratuito para mejorar la productividad y el enfoque. Implementa la técnica Pomodoro: 25 minutos de trabajo concentrado seguidos de 5 minutos de descanso. Permite personalizar los tiempos, agregar tareas con un contador de pomodoros estimados, ver el reporte de tiempo del día y recibir notificaciones. Funciona en el navegador sin instalación.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=pomofocus.io&sz=64',
    tags: ['pomodoro', 'focus', 'productivity'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'clockify',
    title: 'Clockify',
    url: 'https://clockify.me',
    description: 'Aplicación de seguimiento de tiempo 100% gratuita (sin límite de usuarios ni proyectos). Permite registrar las horas trabajadas en diferentes proyectos y tareas, generar reportes detallados y exportarlos. Ideal para freelancers que necesitan facturar por horas, equipos remotos, estudiantes gestionando el tiempo de estudio y cualquier persona que quiera entender en qué invierte su jornada.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=clockify.me&sz=64',
    tags: ['time', 'tracking', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'notion',
    title: 'Notion',
    url: 'https://notion.so',
    description: 'Espacio de trabajo todo-en-uno que combina notas, bases de datos, kanban, wikis y calendarios en una sola aplicación. Su enfoque de "bloques" lo hace extremadamente flexible: puedes crear desde listas de tareas simples hasta sistemas de gestión de proyectos complejos o wikis de equipos. El plan gratuito para uso personal es muy completo. Disponible en web, desktop y móvil.',
    category: 'productivity',
    favicon: 'https://www.google.com/s2/favicons?domain=notion.so&sz=64',
    tags: ['notes', 'database', 'wiki', 'kanban'],
    createdAt: now,
    visitCount: 0,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // AI TOOLS — nuevos
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'gemini',
    title: 'Google Gemini',
    url: 'https://gemini.google.com',
    description: 'El asistente de inteligencia artificial multimodal de Google, potenciado por los modelos Gemini. Puede procesar texto, imágenes, audio y código. Sobresale en razonamiento, programación, análisis de imágenes y en búsqueda de información actualizada gracias a su integración con los servicios de Google. Totalmente gratuito con acceso al modelo Gemini 2.0 Flash, con opción premium para modelos más potentes.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=gemini.google.com&sz=64',
    tags: ['ai', 'google', 'chat'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'ideogram',
    title: 'Ideogram',
    url: 'https://ideogram.ai',
    description: 'Generador de imágenes con IA que destaca por ser uno de los mejores del mercado para renderizar texto dentro de imágenes (logos, carteles, tipografías). Ofrece un plan gratuito diario bastante generoso. Sus estilos van del fotorrealismo a la ilustración, pintura al óleo y pixel art. Las imágenes generadas en el plan gratuito son de uso libre.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=ideogram.ai&sz=64',
    tags: ['ai', 'image', 'generation'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'suno',
    title: 'Suno AI',
    url: 'https://suno.com',
    description: 'Generador de música con IA que crea canciones completas (con letra y voz incluidas) a partir de una simple descripción de texto. Solo describes el género, el estado de ánimo y la temática, y Suno produce una canción de 2-3 minutos con producción musical profesional en segundos. El plan gratuito ofrece 50 créditos diarios para generar canciones.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=suno.com&sz=64',
    tags: ['ai', 'music', 'audio', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'elevenlabs',
    title: 'ElevenLabs',
    url: 'https://elevenlabs.io',
    description: 'La plataforma líder en síntesis de voz con IA, capaz de generar voces hiperrealistas en más de 29 idiomas con control preciso de emoción, tono y cadencia. Ofrece clonación de voz a partir de una muestra de audio. El plan gratuito incluye 10,000 caracteres al mes. Usado para narración de videos, podcasts, audiolibros y asistentes de voz.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=64',
    tags: ['ai', 'voice', 'tts', 'audio'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'gamma',
    title: 'Gamma',
    url: 'https://gamma.app',
    description: 'Herramienta de IA para crear presentaciones, documentos y sitios web de forma ultrarrápida. Describe tu tema y en segundos genera una presentación completamente diseñada con estructura, contenido y gráficos. Las presentaciones resultantes son interactivas, elegantes y mucho más modernas que las de PowerPoint. El plan gratuito permite crear hasta 400 presentaciones.',
    category: 'ai-tools',
    favicon: 'https://www.google.com/s2/favicons?domain=gamma.app&sz=64',
    tags: ['ai', 'presentations', 'slides'],
    createdAt: now,
    visitCount: 0,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // LEARNING — nuevos
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'freecodecamp',
    title: 'freeCodeCamp',
    url: 'https://freecodecamp.org',
    description: 'Plataforma de aprendizaje de programación 100% gratuita y sin anuncios, con más de 3,000 horas de currículo estructurado. Cubre HTML, CSS, JavaScript, React, Python, SQL, APIs y más. Otorga certificaciones reconocidas por la industria al completar los proyectos. Tiene una comunidad enorme y miles de artículos de blog técnicos. Perfecta para aprender desarrollo web desde cero.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=freecodecamp.org&sz=64',
    tags: ['coding', 'free', 'curriculum'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'javascript-info',
    title: 'JavaScript.info',
    url: 'https://javascript.info',
    description: 'Considerado el mejor tutorial moderno de JavaScript en internet. Cubre el lenguaje en profundidad desde los fundamentos (variables, funciones, objetos) hasta temas avanzados (prototipos, closures, async/await, generadores, módulos y APIs del navegador) con explicaciones claras, ejemplos ejecutables en línea y ejercicios. Es gratuito, actualizado y disponible en muchos idiomas.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=javascript.info&sz=64',
    tags: ['javascript', 'tutorial', 'learn'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'css-tricks',
    title: 'CSS-Tricks',
    url: 'https://css-tricks.com',
    description: 'El sitio de referencia más influyente para todo lo relacionado con CSS. Ofrece artículos profundos, guías completas (como la famosa Guía de Flexbox y la Guía de Grid), trucos, técnicas y tutoriales escritos por expertos de la industria. La Almanac de CSS-Tricks es una referencia alfabética de propiedades, selectores y funciones CSS con ejemplos prácticos para cada una.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=css-tricks.com&sz=64',
    tags: ['css', 'reference', 'articles'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'codewars',
    title: 'Codewars',
    url: 'https://codewars.com',
    description: 'Plataforma gratuita de desafíos de programación (llamados "katas") organizados por dificultad. Permite practicar y mejorar tus habilidades resolviendo problemas algorítmicos en más de 55 lenguajes. Después de resolver cada kata puedes ver las soluciones más votadas de otros usuarios, lo que convierte a Codewars en una excelente herramienta para aprender patrones y buenas prácticas.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=codewars.com&sz=64',
    tags: ['challenges', 'algorithms', 'practice'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'webdev',
    title: 'web.dev (Google)',
    url: 'https://web.dev',
    description: 'Plataforma de Google para aprender mejores prácticas de desarrollo web moderno con foco en rendimiento, accesibilidad, SEO y Progressive Web Apps (PWA). Incluye cursos gratuitos, artículos técnicos profundos y guías de medición con Lighthouse. Es la fuente oficial de Google para entender Core Web Vitals y cómo optimizar tu sitio para los estándares del mundo moderno.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=web.dev&sz=64',
    tags: ['web', 'performance', 'pwa', 'google'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'devto',
    title: 'Dev.to',
    url: 'https://dev.to',
    description: 'Comunidad y red social de desarrolladores donde se publican artículos técnicos, tutoriales, experiencias y reflexiones sobre programación. Es un espacio abierto e inclusivo, con contenido de alta calidad sobre temas que van desde consejos de carrera y productividad hasta profundidades de arquitectura de software, herramientas emergentes y novedades de la industria.',
    category: 'learning',
    favicon: 'https://www.google.com/s2/favicons?domain=dev.to&sz=64',
    tags: ['community', 'articles', 'blog'],
    createdAt: now,
    visitCount: 0,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // DATABASES — nuevos
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'neon',
    title: 'Neon',
    url: 'https://neon.tech',
    description: 'PostgreSQL serverless completamente gestionado con un plan gratuito permanente muy generoso (10 GB de almacenamiento, 100 horas de cómputo). Su característica diferenciadora es la "bifurcación instantánea" (branching) de la base de datos: crea copias independientes de tu base de datos en milisegundos para pruebas o previews de pull requests. Escala a cero automáticamente cuando no se usa.',
    category: 'databases',
    favicon: 'https://www.google.com/s2/favicons?domain=neon.tech&sz=64',
    tags: ['postgres', 'serverless', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'firebase',
    title: 'Firebase',
    url: 'https://firebase.google.com',
    description: 'Plataforma de desarrollo de aplicaciones de Google que proporciona una suite completa de herramientas backend: base de datos en tiempo real (Firestore/Realtime DB), autenticación de usuarios, almacenamiento de archivos, hosting, funciones serverless (Cloud Functions), notificaciones push y análisis. El plan gratuito (Spark) es ideal para proyectos personales y prototipos.',
    category: 'databases',
    favicon: 'https://www.google.com/s2/favicons?domain=firebase.google.com&sz=64',
    tags: ['baas', 'realtime', 'google', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'turso',
    title: 'Turso',
    url: 'https://turso.tech',
    description: 'Plataforma de bases de datos SQLite distribuidas al borde (Edge). Construida sobre libSQL (un fork open-source de SQLite), permite tener réplicas de tu base de datos cerca de los usuarios en todo el mundo para latencia ultrabaja. El plan gratuito incluye 500 bases de datos, 9 GB de almacenamiento y 1,000 millones de lecturas al mes. Perfecta para aplicaciones Next.js y Cloudflare Workers.',
    category: 'databases',
    favicon: 'https://www.google.com/s2/favicons?domain=turso.tech&sz=64',
    tags: ['sqlite', 'edge', 'serverless'],
    createdAt: now,
    visitCount: 0,
  },

  // ──────────────────────────────────────────────────────────────────────────
  // CUSTOM / ENTRETENIMIENTO Y OTROS
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: 'desmos',
    title: 'Desmos Graphing Calculator',
    url: 'https://desmos.com/calculator',
    description: 'La calculadora gráfica interactiva más elegante y potente disponible en el navegador, completamente gratuita. Permite graficar funciones matemáticas complejas, crear animaciones con parámetros deslizantes, explorar transformaciones geométricas, resolver ecuaciones y compartir las gráficas con un enlace. Usada en matemáticas, física, ingeniería y preparación para exámenes en todo el mundo.',
    category: 'custom',
    favicon: 'https://www.google.com/s2/favicons?domain=desmos.com&sz=64',
    tags: ['math', 'graphing', 'calculator', 'free'],
    createdAt: now,
    visitCount: 0,
  },
  {
    id: 'haveibeenpwned',
    title: 'Have I Been Pwned',
    url: 'https://haveibeenpwned.com',
    description: 'Servicio gratuito y de confianza creado por el experto en seguridad Troy Hunt. Permite verificar si tu dirección de email o número de teléfono ha aparecido en alguna filtración de datos conocida (data breach). Monitorea miles de filtraciones y es usado por millones de personas para saber si sus credenciales están comprometidas. También ofrece suscripciones de alerta gratuitas.',
    category: 'custom',
    favicon: 'https://www.google.com/s2/favicons?domain=haveibeenpwned.com&sz=64',
    tags: ['security', 'privacy', 'breach'],
    createdAt: now,
    visitCount: 0,
  },
];

export function getCategoryById(id: string): Category | undefined {
  return CATEGORIES.find(c => c.id === id);
}

